"""added credits and cation for splash

Revision ID: 2f914b4847c0
Revises: f1a6a4f5c8f2
Create Date: 2024-03-06 20:27:50.690053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f914b4847c0'
down_revision = 'f1a6a4f5c8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('splash_caption', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('splash_credit', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('splash_credit')
        batch_op.drop_column('splash_caption')

    # ### end Alembic commands ###
