"""verify v2

Revision ID: 596af5a94ffa
Revises: 674cd7846b37
Create Date: 2024-03-17 23:48:49.115542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '596af5a94ffa'
down_revision = '674cd7846b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('verificated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
