"""verify

Revision ID: 674cd7846b37
Revises: b5c4bda8b4c0
Create Date: 2024-03-17 23:47:27.545498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674cd7846b37'
down_revision = 'b5c4bda8b4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('verificated')

    # ### end Alembic commands ###
