"""post views

Revision ID: 7330d4e6d80c
Revises: fee0b32850f2
Create Date: 2024-03-09 17:07:25.072491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7330d4e6d80c'
down_revision = 'fee0b32850f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('post_views')

    # ### end Alembic commands ###
