"""comments disabled

Revision ID: afb5769a6bc6
Revises: dd11fc4edaef
Create Date: 2024-03-06 14:06:42.889732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb5769a6bc6'
down_revision = 'dd11fc4edaef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments_disabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.drop_column('comments_disabled')

    # ### end Alembic commands ###
