"""more bits

Revision ID: f1a6a4f5c8f2
Revises: afb5769a6bc6
Create Date: 2024-03-06 20:12:21.941401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1a6a4f5c8f2'
down_revision = 'afb5769a6bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.alter_column('splash_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_posts', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=10000),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('splash_url',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
